---
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https tor curl

install:
  # install release version v0.74.2
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.74.2/hugo_extended_0.74.2_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.74.2_Linux-64bit.deb

# script - run the build script
script:
  - hugo

deploy:
  provider: page
  skip_cleanup: true
  github-token: e2e9c3900ae151bc30b7ed572395c38e92ed92c6
  email: kencho.gigascience@gmail.com
  name: kencho51
  verbose: true
  keep-history: true
  local_dir: public
  on:
    branch: master