---
language: go

dist: xenial

env:
  - HUGO_VERSION="0.74.2"

before_install:
  - sudo apt-get update -qq

install: true

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  # install release version v0.74.2
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
  - rm -rf public || exit 0

# script - run the build script
script:
  - hugo --gc -v --minify

deploy:
  provider: page
  skip_cleanup: true
  github_token: 30398cce5cbe77d25bfc98dff066ba33e369b585
  email: "kencho.gigascience@gmail.com"
  name: "kencho51"
  verbose: true
  keep_history: true
  local_dir: public
  repo: "kencho51/kencho51.github.io"
  target-branch: master
  on:
    branch: master