---
dist: xenial

env:
  - HUGO_VERSION=0.74.2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -yq install apt-transport-https tor curl


install: true

before_script:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  # install release version v0.74.2
  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb

# script - run the build script
script:
  - hugo --gc -v

deploy:
  provider: page
  skip_cleanup: true
  github_token: "18a6c6fcbc7f74287e3ff369afa03a127a551cfb"
  email: "kencho.gigascience@gmail.com"
  name: "kencho51"
  verbose: true
  keep_history: true
  local_dir: public
  on:
    branch: develop