language: go
dist: xenial
go:
  - master
before_install:
  - sudo apt-get update -qq
install:
  - go get github.com/gohugoio/hugo
before_script:
#  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
#  - sudo dpkg -i hugo_${HUGO_VERSION}_Linux-64bit.deb
  - rm -rf public || exit 0
script:
  - hugo --gc -v --minify
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  email: kencho.gigascience@gmail.com
  name: kencho51
  repo: kencho51/kencho51.github.io
  verbose: true
  on:
    branch: master
