baseurl: "http://localhost:1313/"
params:
  env: "development"
  googleAnalytics: ""  # Disable analytics for local development
  googleSiteVerification: ""  # Disable verification for local development 