baseurl: "https://blog.superbrains.cc/"
title: "kencho51"
theme: "hugo-PaperMod"
languageCode: "en-us"
copyright: "kencho51"
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
pygmentsCodefences: true
enableRobotsTXT: true
minify:
  disableXML: true
  minifyOutput: true

# SEO and Performance
enableGitInfo: true
enableEmoji: true
enableMissingTranslationPlaceholders: false

# Sitemap configuration
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

# RSS configuration
rssLimit: 20
rssFullContent: true

# publishDir: "gigathing"

pagination:
    pagerSize: 5

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home:
    - HTML
    - RSS
    - JSON

services:
  disqus:
    shortname: "cloudpage"

# SEO Meta tags
params:
  # env: "production"  Default is production when running hugo and development when running hugo server
  mainSections: ["post"]
  homeInfoParams:
    Title: Hi there
    Content: Welcome to my blog!
  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/kencho51"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/cholingken/"
    - name: "Orcid"
      url: "https://orcid.org/0009-0006-9057-8835"
  opengraph: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "telegram", "email"]
  ShowReadingTime: true
  ShowWordCount: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true

  # SEO Meta tags
  description: "Personal tech blog covering development tutorials, insights, and experiences in software development, DevOps, and technology."
  keywords: ["tech blog", "software development", "tutorials", "programming", "devops", "technology"]
  author: "kencho51"
  
  # Social media
  twitter:
    site: "@kencho51"
    creator: "@kencho51"
  
  # Additional SEO
  googleAnalytics: "G-LV12W6L6C4"
  googleSiteVerification: "G-LV12W6L6C4"
  
  # Structured data
  structuredData: true
  
  # Performance
  enableFingerprinting: true
  enableSourceMap: false

  # Analytics configuration
  analytics:
    google:
      SiteVerificationTag:: "G-LV12W6L6C4"

  # Search configuration for PaperMod
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  # dateFormat: "Mon, Jan 2, 2020"

permalinks:
  post: "/:contentbasename/"

menu:
  main:
    - name: "About"
      url: "/page/about/"
      weight: 1
    - name: "Search"
      url: "/search/"
      weight: 4
    - name: "Tech"
      url: "/post"
      weight: 2
    - name: "Projects"
      url: "/projects/"
      weight: 3