baseurl: "https://gigathing.pages.dev/"
title: "kencho51"
theme: "hugo-PaperMod"
languageCode: "en-us"
copyright: "kencho51"
pygmentsUseClasses: true
pygmentsCodefences: true
# publishDir: "gigathing"

taxonomies:
  tag: "tags"

outputs:
  home:
    - HTML
    - RSS
    - JSON

services:
  disqus:
    shortname: "cloudpage"

params:
  mainSections: ["post"]
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...
  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/kencho51"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/cholingken/"
    - name: "Orcid"
      url: "https://orcid.org/0009-0006-9057-8835"
  opengraph: true
  # ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  comments: true

  # Analytics configuration
  analytics:
    google:
      id: "G-LV12W6L6C4"

  # Search configuration for PaperMod
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  # dateFormat: "Mon, Jan 2, 2020"

permalinks:
  post: "/:contentbasename/"

menu:
  main:
    - name: "About"
      url: "/page/about/"
      weight: 1
    - name: "Search"
      url: "/search/"
      weight: 4
    - name: "Tech"
      url: "/post"
      weight: 2
    - name: "Projects"
      url: "/projects/"
      weight: 3